---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bekk-ws-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.bekk.no
  resources:
  - businesshoursscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.bekk.no
  resources:
  - businesshoursscalers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.k8s.bekk.no
  resources:
  - businesshoursscalers/status
  verbs:
  - get
  - patch
  - update
